In [23]:
import torch
import numpy as np

In [7]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [9]:
print(t[:,:-1]) #전체에서 마지막 column을 제외하고 출력 = numpy와 slicing 개념이 비슷하다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [15]:
#Torch에서는 BroadCasting방법이 사용된다. 크기가 서로 다른 행렬의 사칙연산을 자동으로 수행을 해주는 기능.
#Vector + Matrix
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]

In [21]:
#최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴합니다.
t2 = torch.FloatTensor([[1, 2], [3, 4]])
print(t2.max(dim = 0)) #max() 메소드에 dim인자를 넣으면 자동으로 아그맥스를 찾아준다. 
print(t2.argmax(dim = 0))

print('Max: ', t2.max(dim=0)[0]) #index를 이용하여 max값만 받고 싶어하면 받으면 된다.
print('Argmax: ', t2.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([1, 1])
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [24]:
#뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경 = 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다.
t3 = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t3)

In [26]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경, numpy의 reshape역할과 -1 동일.
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [30]:
#스퀴즈(Squeeze) - 1인 차원을 제거한다.
#언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

ft2 = torch.Tensor([0, 1, 2])
print(ft2.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
torch.Size([3])


In [32]:
print(ft.squeeze())
print(ft.squeeze().shape) #3x1 텐서가 (3,)으로 변경되었다. 

print(ft2.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft2.unsqueeze(0).shape)

tensor([0., 1., 2.])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
#ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print()
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기 = np.ones
print()
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기 = np.zeros 

tensor([[0., 1., 2.],
        [2., 1., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])
