In [12]:
#Natural Language Processing(NLP)
from tensorflow.keras.preprocessing.text import text_to_word_sequence, Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

import numpy as np
import tensorflow as tf


In [4]:
text = "Make it without Noting"
result = text_to_word_sequence(text)
print(result)

['make', 'it', 'without', 'noting']


In [6]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_counts) #단어의 빈수도 수를 계산한 결과를 출력, orderdict는 순서를 기억하는 용도
print(token.document_count) #몇 개의 문장이 있는 지도 확인할 수 있다.

OrderedDict({'먼저': 1, '텍스트의': 2, '각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '결과는': 1, '사용할': 1, '수': 1, '있습니다': 1})
3


In [7]:
#one-hot encoding은 문장에서 단어의 index를 불러와 one-hot encoding을 한다. vector의 크기는 n+1이 된다.

In [13]:
#word embedding 단어를 vector space에 두는 것.

docs2 = ['너무 재밌네요', '최고에요', '참 잘 만든 영화에요', '추천하고 싶은 영화입니다.','한 번 더 보고 싶네요', '글쎄요', '별로에요', '생각보다 지루하네요'
         ,'연기가 어색해요','재미없어요']
#긍정 리뷰는 1 부정 리뷰이면 0을 한다.
classes = np.array([1,1,1,1,1,0,0,0,0,0])

#토큰화
token = Tokenizer()
token.fit_on_texts(docs2)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고': 14, '싶네요': 15, '글쎄요': 16, '별로에요': 17, '생각보다': 18, '지루하네요': 19, '연기가': 20, '어색해요': 21, '재미없어요': 22}


In [22]:
x = token.texts_to_sequences(docs2)
print(x)

#padding 딥러닝 모델에 입력을 하려면 토큰의 길이가 일정해야한다.
padded_x = pad_sequences(x,4) #서로 다른 길이의 데이터를 4로 맞추기
print('\n',padded_x)

#임베딩을 하기 위해 워드의 size input값을 알려준다.
word_size = len(token.word_index)+1

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14, 15], [16], [17], [18, 19], [20, 21], [22]]

 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]


In [25]:
#모델 구성하기
model = Sequential()
model.add(Embedding(word_size, 8)) #임베딩은 word_size만큼 input output은 8개, 계산 길이는 padding 4로 했기 때문에 4
model.add(Flatten()) #model 층에 들어갈 때는 1차원 길이로 들어가야 하기 때문에 Flatten()함수를 이용
model.add(Dense(1, activation='sigmoid')) #리뷰의 값이 1 또는 0이기 때문에 sigmoid를 사용하고 output 결과를 1개.

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(padded_x,classes, epochs=20)

print('\n Accuracy : %.4f' %(model.evaluate(padded_x,classes)[1]))

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 856ms/step - accuracy: 0.4000 - loss: 0.6949
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6914
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6897
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6000 - loss: 0.6845
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6000 - loss: 0.6828
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7000 - loss: 0.6811
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7000 - loss: 0.6794
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7000 - loss: 0.6776
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7000 - loss: 0.6759
