In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
seed = 1
torch.manual_seed(seed)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함. require_grad는 학습 중 계속 변수가 변한다는 것을 의미한다.
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)
print(W) #(1,) vector이다.
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [9]:
#Hypothesis 식 세우기
H_x = x_train*W +b
print(H_x)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [14]:
#비용함수 = 오차함수 정의하기 
cost = torch.mean((y_train-H_x)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [15]:
optimizer = optim.SGD([W,b], lr=0.01)

# gradient를 0으로 초기화
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [16]:
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/1999 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/1999 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/1999 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/1999 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/1999 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/1999 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.000 Cost: 0.000000
